eyre: lower +channel-timeout
urbit/urbit pull request #3670
Opened 2020-10-08 03:04 UTC by liam-fitzgerald

Eyre does not reap active channels with an associated eventstream.
+channel-timeout is only used when we lose the eventstream, to allow for
a client to re-establish a subscription without having to resend updates
that had already been received. However, this feature is unused in landscape
and the length of the timeout has been causing bail:memes as of late. As such,
this commit changes +channel-timeout to reap more often to avoid potential
memory pressure issues

2020-10-08 03:08 UTC, tylershuster commented
This must be why I have a gig of channels

2020-10-08 14:03 UTC, matildepark commented
> If it doesn't, does that mean that, whenever I drive through a tunnel, my urbit re-initiates all subscriptions etc once it regains a connection?

IIRC, Yes — we clear and re-reduce the initial update.

2020-10-08 15:39 UTC, eglaysher requested changes
I am against this for the reasons palfun said above.

A better workaround, assuming that this can't be fixed in landscape, is to add to eyre the same subscription backoff logic that ames uses, so that a subscription that has a large queue of unacked messages breaks the individual subscription, which should be a detectable state in the channel, so that the channel queues don't become so large in the first place.

2020-10-13 19:23 UTC, tacryt-socryp commented
I think this can be closed.

2020-10-13 22:05 UTC, closed without merging