Chat perf
urbit/urbit pull request #3772
Opened 2020-10-21 19:57 UTC by tylershuster

The code is still a bit messy but the ideas in this are:

- [ ] Rewrite sigils to use `Blob` URLs, one per sigil to allow caching and reduce render size
- [X] Rewrite `VirtualScroller` to use a `placeholderRenderer` to allow lightweight (searchable) virtualized elements
- [X] Rate-limit `onscroll`
- [ ] Indigoify along the way

2020-10-21 22:01 UTC, tylershuster commented
There's now a global `Map` that keeps track of every unique sigil and the blob URL for it. It doesn't do garbage collection, but I mean it can only be 4 billion entries, right?

2020-10-21 22:03 UTC, tylershuster commented
Note that search is a *little* funky because when you search for something, the browser hits the unrendered version of it, then jumps to it, forcing a rerender and the node no longer exists. I'm hesitant to make a `PureComponent` version of the rendered text that can be shuffled in and out of containers, but I think it's the only way to get really nice search. Would appreciate impressions.

2020-11-06 16:24 UTC, tylershuster commented
I'm ready for other people's perception of this, whether whole or in piecemeal.

I can't generate objective data on performance (but I'm open to suggestions) but it *feels* faster, and it allows searching the entire loaded log of text, even if it is a little "bouncy" — i.e. you might have to do the search a few times as the component renders in. I think it's a good start at least.

2020-11-06 17:53 UTC, matildepark commented on pkg/interface/src/logic/lib/sigil.js
> +      <img
`BaseImage` in indigo-react? :p

2020-11-06 18:42 UTC, matildepark requested changes
Sigils aren't looking quite right here. 

<img width="535" alt="image" src="https://user-images.githubusercontent.com/20846414/98402549-7b5d4e00-2035-11eb-8ca8-98f6bb847808.png">

There's a strange behaviour where chat scrolling is slower the more messages there are; small DMs are zippy but UC rooms are pretty sluggish to scroll through. Unsure how to address that though.

2020-11-12 03:48 UTC, tylershuster commented
Ok, let's just go with this. If it works it works. Much fewer nodes with the SVGs as images.

2020-11-19 15:34 UTC, tylershuster commented
@matildepark

2020-11-19 18:56 UTC, matildepark commented
Will test.

2020-11-19 19:22 UTC, matildepark commented
Sigils still quite wonky, need padding and the surrounding border often pokes out.

Compare livenet vs. dev:

<img width="511" alt="image" src="https://user-images.githubusercontent.com/20846414/99713573-7b683f80-2a72-11eb-88d2-58045a6f233c.png">


<img width="520" alt="image" src="https://user-images.githubusercontent.com/20846414/99713523-6c818d00-2a72-11eb-851b-17cbb70f6954.png">

<img width="162" alt="image" src="https://user-images.githubusercontent.com/20846414/99713649-92a72d00-2a72-11eb-8675-51d714a3bf63.png">

2020-12-04 04:43 UTC, closed without merging