chat: fixed embedded scroll item disability
urbit/urbit pull request #3802
Opened 2020-10-27 00:01 UTC by tylershuster

Fixes #3801

This just checks if the thing we're hovered over as we're scrolled has *its own* scrollbar, and doesn't apply the inversion and subsequent pseudoscroll if so

2020-10-27 17:30 UTC, matildepark requested changes
This has some *really* weird side effects if you're scrolling over code blocks that actually instigates the "embed reverses scroll direction" case, even if the code block doesn't even have a scrollbar.

2020-10-27 17:31 UTC, matildepark commented
Here's me scrolling continuously *up*, getting scrolled down once I hit the code block container.
![Oct-27-2020 13-30-59](https://user-images.githubusercontent.com/20846414/97339234-b5ba3480-1858-11eb-90bd-23ea90b4214d.gif)

2020-10-27 21:05 UTC, tylershuster commented
See comments for explanation

2020-10-28 01:08 UTC, matildepark commented
Fix commits?

2020-10-28 23:35 UTC, tylershuster commented
Commits fixed

2020-10-30 00:25 UTC, matildepark approved these changes

2020-10-30 00:25 UTC, merged