publish: fixes #3859, fixes #3844
urbit/urbit pull request #3860
Opened 2020-11-02 20:19 UTC by tylershuster

This is the same fix as https://github.com/urbit/urbit/pull/3856

@liam-fitzgerald does this have something to do with the work you mentioned on bigints earlier? `===` checks are failing because of a JS variable type and I haven't looked deeply into it but my intuition tells me a) that's the issue and b) you might know something about a holistic pass to remedy the issue rather than adding `valueOf()` piecemeal

2020-11-02 20:23 UTC, matildepark commented
Tagging @liam-fitzgerald for possible holistic solution; if this thread is left pending around the next OTA I will merge this as is

2020-11-03 07:30 UTC, liam-fitzgerald requested changes
should change this so that the revision number is a JS number.

2020-11-03 07:30 UTC, liam-fitzgerald commented on pkg/interface/src/views/apps/publish/components/EditPost.tsx
> +        return rev.valueOf() === newRev;
`getLatestRevision` in `lib/publish.ts` should be changed such that `return [revNum.toJSNumber(), title.text, body.text, rev.post]`; is the return value.

2020-11-03 14:51 UTC, tylershuster commented
Cheers @liam-fitzgerald — now we don't need https://github.com/urbit/urbit/pull/3856 but it won't hurt

2020-11-03 15:59 UTC, liam-fitzgerald approved these changes
LGTM!

2020-11-03 17:17 UTC, merged