graph-push-hook: allow for node removal by author
urbit/urbit pull request #3865
Opened 2020-11-03 00:23 UTC by liam-fitzgerald

2020-11-03 17:05 UTC, matildepark commented
This should probably include FE changes in the PR?

2020-11-03 17:21 UTC, liam-fitzgerald commented
ruh roh

2020-11-03 17:27 UTC, matildepark commented
Is that prohibitive? We just want to avoid a situation where back-end and front-end changes are deviated and it's unclear which support which.

2020-11-03 17:29 UTC, liam-fitzgerald commented
no, I just forgot accidentally

2020-11-03 17:53 UTC, tacryt-socryp commented on pkg/arvo/app/graph-push-hook.hoon
> +  %+  levy
What does this do? The method description in the standard library is... not helpful.

2020-11-03 17:54 UTC, tacryt-socryp commented on pkg/arvo/app/graph-push-hook.hoon
> +  %+  levy
Oh, okay. It just returns yes if all of the result tests are yes... essentially an ?& across a list.

2020-11-03 17:59 UTC, tacryt-socryp commented on pkg/arvo/lib/graph.hoon
> +++  get-node
Technically this is "got-node", as "get-node" would return a unit.

2020-11-03 17:59 UTC, tacryt-socryp requested changes
One small change (get to got), otherwise looks good.

2020-11-05 04:19 UTC, tacryt-socryp approved these changes

2020-11-05 04:20 UTC, merged