AsyncButton: protect against double submit
urbit/urbit pull request #3877
Opened 2020-11-03 19:23 UTC by liam-fitzgerald

Disables `AsyncButton` if the form is submitting, to prevent accidental double submits.

Design: it makes the new channel screen look this (note the different color of the button):
![Capture d’écran 2020-11-04 à 5 19 35 AM](https://user-images.githubusercontent.com/46801558/98031104-bd339c00-1e5d-11eb-8469-082dc95c8822.png)

cc: @urcades

2020-11-03 19:26 UTC, matildepark approved these changes
Seems fine — design feedback is sort of built-in for indigo components and disabled when submitting is expected

2020-11-03 19:46 UTC, urcades commented
Yeah, note the following Indigo structure for button styling:

[image: Screen Shot 2020-11-03 at 2.41.44 PM.png]

No dimming is implied here, but I think disabling the cursor via the css
property 'not-allowed'
<https://www.w3schools.com/cssref/playit.asp?filename=playcss_cursor&preval=not-allowed>
is enough to signal what's needed to be signaled here.

—
~fabled-faster
https://urbit.org/


On Tue, Nov 3, 2020 at 2:26 PM matildepark <notifications@github.com> wrote:

> *@matildepark* approved this pull request.
>
> Seems fine — design feedback is sort of built-in for indigo components and
> disabled when submitting is expected
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/urbit/urbit/pull/3877#pullrequestreview-522810375>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJD2Y4ZFF55JWB2GNF3Q6LSOBKN7ANCNFSM4TJEVPDQ>
> .
>

2020-11-03 19:48 UTC, tylershuster commented
Image missing @urcades

2020-11-03 19:53 UTC, urcades commented
Ah, I forget the image discrepancy between responding via email and responding in github:

<img width="394" alt="Screen Shot 2020-11-03 at 2 41 44 PM" src="https://user-images.githubusercontent.com/1195363/98034038-5faf3900-1de4-11eb-9a00-d1d3b51d5a08.png">

2020-11-04 18:07 UTC, matildepark requested changes
Holding off on merge until it resembles design — 
<img width="394" alt="image" src="https://user-images.githubusercontent.com/20846414/98151817-c1cc7480-1e9e-11eb-85f6-6da2fbe9d406.png">

2020-12-03 03:38 UTC, closed without merging