interface: add debug shim to store
urbit/urbit pull request #4334
Opened 2021-01-25 23:57 UTC by liam-fitzgerald

adds window.debugStore() to show past actions based on the tag and the
current state of some slice of the store. Logs the past 15 actions for
each tag.

cc: @tylershuster how can we get something similar for the zustand based store?

2021-01-26 00:00 UTC, tylershuster commented
Yeah, I've been thinking I need to make an abstract class to build the state stores on top of anyway. If we intercept the `setState` function and add a `debugStore` function to that abstract class that all the state stores extend, we should be able to get a list of recent transformations per store

2021-01-26 21:04 UTC, matildepark requested changes
This doesn't actually seem to function in practice. No matter where I navigate, what messages I send, or what notifications I dismiss, I get

<img width="349" alt="image" src="https://user-images.githubusercontent.com/20846414/105905191-23a90000-5ff0-11eb-9923-1f482578ee8a.png">

2021-01-27 02:44 UTC, liam-fitzgerald commented
You have to pass it the mark of the update eg "harkUpdate"

2021-01-27 23:24 UTC, matildepark approved these changes
My bad.

2021-01-27 23:24 UTC, merged