fix URL regex on tokenizeMessage.js
urbit/urbit pull request #4430
Opened 2021-02-12 05:27 UTC by mirtyl-wacdec

Tiny fix to the URL regex so that it doesn't store punctuation marks (e.g. ",") inside the urls, breaking the links.

2021-02-16 19:38 UTC, matildepark requested changes
Does what it says. Thanks for the first contribution! But please adhere to [commit hygiene](https://github.com/urbit/urbit/blob/master/CONTRIBUTING.md#hygiene) — you'll want to format this commit like "landscape: ignore punctuation tokenizing URLs" or the like.

You'd rebase, reword and force push this PR as so:

Checkout `patch-2` on your fork.

```
git merge-base master patch-2
git rebase -i [that commit hash]
```

Note we write 'master' because this branch was branched off master. Don't always do master if you branch off next-js!

Change 'pick' on the commit to 'reword', change the wording, then `git push -f`.

2021-02-23 21:45 UTC, matildepark commented
Just realised you formatted the PR *title* — I mean the commit itself you made here. @mirtyl-wacdec

2021-02-26 17:58 UTC, mirtyl-wacdec commented
Very sorry, my git foo is rather miserable and I didn't have this account set up on my CLI. Did this work?

2021-02-26 18:29 UTC, matildepark commented
Yeah, it did.

2021-02-26 18:30 UTC, matildepark approved these changes

2021-02-26 18:30 UTC, merged