settings: sidebar same width as groups
urbit/urbit pull request #4579
Opened 2021-03-10 21:23 UTC by jamesacklin

Adjusts the System Preferences layout to be the same (CSS grid-based) as Groups and Messages.

The sidebar in both instances is flexible. The proportions match, therefore so do the pixel measurements at various window widths.

![comparison](https://user-images.githubusercontent.com/748181/110698949-4831f380-81bc-11eb-9dcf-699825ffe327.png)

An easy way to test is to visit the System Preferences, Leap to a Group, then use browser keyboard shortcuts to quickly flip back and forth between pages.

Fixes urbit/landscape#541

2021-03-10 21:58 UTC, urcades approved these changes
I meant to write what I wrote here:

https://github.com/urbit/landscape/issues/541#issuecomment-796189061

In this PR, but the sentiment still holds — it's looking great, but if you have a better sense/thought around how to modify the width, go right ahead!

2021-03-11 01:45 UTC, matildepark requested changes
This seems not desired

<img width="1522" alt="image" src="https://user-images.githubusercontent.com/20846414/110723108-8988ca00-81e1-11eb-8249-905b9d11d271.png">

2021-03-11 17:42 UTC, jamesacklin commented
> This seems not desired

Fixed by yanking the bonus Row container. 

![image](https://user-images.githubusercontent.com/748181/110830347-1d50a980-8267-11eb-8638-fe6f30279f3d.png)

Also appropriately padded the Back button on mobile.

![image](https://user-images.githubusercontent.com/748181/110830466-3eb19580-8267-11eb-894b-398c4f68a0ec.png)

2021-03-11 21:52 UTC, matildepark approved these changes

2021-03-11 21:52 UTC, merged