Native Windows urbit binaries using MingW
urbit/urbit pull request #4675
Opened 2021-03-27 20:57 UTC by locpyl-tidnyd

This PR will enable C urbit binaries to build and run natively on Windows using MingW, albeit for now without CLI terminal functionality.

The commits pushed to this PR as of 03/27 contain changes that improve portability, but no MingW-specific code yet. I will continue adding to this PR as I sort out changes in my local repo.

/cc @joemfb

2021-03-28 09:17 UTC, Fang- commented
> albeit for now without CLI terminal functionality

Is this running up against Window's lack of ansi terminal emulation and/or general compatibility in that area? Curious to hear what you think it would take to support this.

In any case: very cool stuff, thank you!

2021-03-28 20:15 UTC, ohAitch commented
I think in that case you could run it in PuTTY? (Or VSCode or for that matter Windows Terminal)

2021-03-28 20:40 UTC, locpyl-tidnyd commented
In more recent Windows 10, the default console actually supports VT escape characters as an opt-in, but the good old Win32 console functions should be enough to implement the terminal. In fact, I suspect that one could even get by with just `\r` and '\b` and turning off echo. The real answer is that I did not consider the terminal a high priority item. Everyone, myself included, uses herb/http via lens port to talk to ships running in the background anyway. Also, the code in term.c is rather hairy and I've never used termios/termcaps before, so I concentrated on [getting ships off the ground](https://istheshipstillstuck.com/) first.

2021-03-28 20:41 UTC, locpyl-tidnyd commented
In more recent Windows 10, the default console actually supports VT escape characters as an opt-in, but the good old Win32 console functions should be enough to implement the terminal. In fact, I suspect that one could even get by with just `\r` and `\b` and turning off echo. The real answer is that I did not consider the terminal a high priority item. Everyone, myself included, uses herb/http via lens port to talk to ships running in the background anyway. Also, the code in term.c is rather hairy and I've never used termios/termcaps before, so I concentrated on [getting ships off the ground](https://istheshipstillstuck.com/) first.

2021-03-29 22:04 UTC, Fang- commented
> the code in term.c is rather hairy

#4463 intends to make it a bit less hairy (and also refactors the terminal protocol a little bit). You may or may not want to develop/test against that if you end up putting in a lot of term.c work. Also happy to hop on a call or email thread or w/e and walk you through the codebase, if that's useful to you!

If you want to fully support all functionality, you'll need to get fancier than just `\r` `\b`. You can imagine getting smart about down-converting output that's too complex for Win32 consoles to properly render, but at that point you have to ask yourself what you want the terminal for in the first place.

2021-03-30 15:39 UTC, locpyl-tidnyd commented
@Fang- I looked at what you are doing in term.c in #4463, and it seems to be all above the plumbing layer I am concerned with: the layer that provides you with fds/`uv_stream_t*`s that support VT escapes, and switches them to/from raw mode on request. I'm going to try to migrate it to `uv_tty_t` and let libuv do most of the heavy lifting. `uv_tty_t` does VT emulation itself when it detects that Windows doesn't understand it. The only problem place in term.c for me is the use of `write(2)` in `_term_spin_step()` at a time when the terminal is (I think) in raw mode, as escapes and unicode characters written past libuv may not be interpreted. It _sort of_ works as-is on Windows 10, but rewriting it so that it uses `uv_write` would be cleaner.

2021-03-30 15:50 UTC, locpyl-tidnyd commented
@Fang- Thank you. I have since gone over term.c a couple times trying to refactor plumbing, and while I still don't understand the dill/drum logic, luckily I find that I don't really have to. I looked at what you are doing in term.c in #4463, and it seems to be all above the bottommost plumbing layer I am concerned with: the layer that provides you with fds/`uv_stream_t*`s that support VT escapes, and switches them to/from raw mode on request. I'm going to try to migrate it to `uv_tty_t` and let libuv do most of the heavy lifting. `uv_tty_t` does VT emulation itself when it detects that Windows doesn't understand it. The only problem place in term.c for me is the use of `write(2)` in `_term_spin_step()` at a time when the terminal is (I think) in raw mode, as escapes and unicode characters written past libuv may not be interpreted. It _sort of_ works as-is on Windows 10, but rewriting it so that it uses `uv_write` would be cleaner.

2021-03-30 16:57 UTC, joemfb commented
@locpyl-tidnyd, the terminal is (almost) always in raw mode. The spinner was written that way (stealing the fd, writing synchronously) because it used to run on its own thread, and I haven't seen a need to change it.

If `term.c` gives you too much trouble, it might be reasonable for the first pass to just disable it entirely (as `-t` does).

2021-03-31 14:49 UTC, locpyl-tidnyd commented
I've added console support that works in native Windows console. Console does weird stuff if urbit is started from a console emulator such as ConEmu, Msys or Cygwin, because an emulated console is completely different from a native Windows console, but I try to detect this situation and warn the user that it's not supported.

2021-04-01 16:33 UTC, locpyl-tidnyd commented
The latest changes fix most of the remaining terminal issues and enable basic daemon mode. The situation is as follows:
- `-d` now makes the urbit process detach from the native Windows console, if any, and redirect standard handles that used to be attached to the console to `/dev/null`. (If output was redirected to a file or pipe, it is not affected.) `-d` does nothing if urbit is run from a console emulator. I could make it "fork" away (Windows does not have `fork(2)` so it's a bit more complex), but I don't think it's worth bothering with. urbit.exe can be launched directly from Run or from a shortcut, or, to avoid having its console blink even briefly, with `start /b` or suitable task scheduler options. If launching it with `CreateProcess` then `CREATE_NO_WINDOW` and `DETACHED_PROCESS` flags should behave as expected.
- Live terminal works okay in native Windows console and almost okay in console emulators that use named pipes to communicate with their "terminal" processes (some startup messages may be slightly garbled, so I've left the "experimental support" message in).
- The new job I added to the `build.yml` workflow builds static Windows binaries. It does not strip them of debugging symbols, which would make sense for release, but releasing is above my (present) pay grade.

Given all this, I am opening this PR for review.

2021-04-01 16:37 UTC, locpyl-tidnyd commented
The latest changes fix most of the remaining terminal issues and enable basic daemon mode. The situation is as follows:
- `-d` now makes the urbit process detach from the native Windows console, if any, and redirect standard handles that used to be attached to the console to `/dev/null`. (If output was redirected to a file or pipe, it is not affected.) `-d` does nothing if urbit is run from a console emulator. I could make it "fork" away (Windows does not have `fork(2)` so it's a bit more complex), but I don't think it's worth bothering with. urbit.exe can be launched directly from Run or from a shortcut, or, to avoid having its console blink even briefly, with `start /b` or suitable task scheduler options. If launching it with `CreateProcess` then `CREATE_NO_WINDOW` and `DETACHED_PROCESS` flags should behave as expected.
- Live terminal works okay in native Windows console. It works _almost_ okay in console emulators that use named pipes to communicate with their "terminal" processes: a few startup messages may be slightly garbled, so I've left the "experimental support" message in.
- The new job I added to the `build.yml` workflow builds static Windows binaries. It does not strip them of debugging symbols, which would make sense only for release.

Given all this, I am opening this PR for review.

2021-04-30 20:19 UTC, locpyl-tidnyd commented
Changed `-d` to work in the same manner on MingW as it does on other systems: the initial process creates a child that does the actual work, waits for it to boot, and then exits. This has enabled me to add a smoke test to `build.yml` which boots a fake `~zod` and shuts it down with a lens request.

One limitation, due to how Windows console handles work internally, is that if `-d` is used from the native Windows console and stdout/stderr are not redirected, then no ship output will be visible. This is awkward to work around, and daemon mode is intended for starting background processes anyway, so I consider having no output in this case to be an acceptable compromise.

2021-04-30 20:29 UTC, locpyl-tidnyd commented
Changed `-d` to work in the same manner on MingW as it does on other systems: the initial process creates a child that does the actual work, waits for it to boot, and then exits. This has enabled me to add a smoke test to `build.yml` which boots a fake `~zod` and shuts it down with a lens request.

One limitation, due to how Windows console handles work internally, is that if `-d` is used from the native Windows console and stdout/stderr are not redirected, then no ship output will be visible. This is awkward to work around, and daemon mode is intended for starting background processes anyway, so I consider having no output in this case to be an acceptable compromise. If you want to see ship output in the native console, use `-t`.

2021-06-03 23:04 UTC, joemfb requested changes
My apologies for the long delay. This is excellent work.

I've tested this branch pretty extensively now, and both the build scripts and resulting binary are working quite well.

I've reviewed the changes above, requesting clarification around some of the more complicated pieces, suggested some small tweaks, and noted potential future improvements. Some further notes:

### build:

- the "poor man's nix shell" extends `*-sources.json` with a `mingw` object to configure the build. this probably precludes future use of `nim` to manage those sources (i've been updating them manually anyway, /cc @brendanhay)

### patches:

- libh2o is patched to workaround windows opposite `iovec` member order with a new `STRLIT` macro, and to disable functionality around `AF_UNIX` sockets
- lmdb is patched to fix it's error-logging string allocation

### known issues:

- `mmap()` with `MAP_FIXED` very rarely runs into issues due to ASLR (see https://stackoverflow.com/questions/41079506/how-to-reserve-memory-on-windows-and-later-map-files-into-it)
- the terminal does not work well inside terminal emulators (works great in `cmd.exe`, haven't tested Windows Terminal)
- ctrl-z (ungraceful exit) is not implemented. I don't think this is particularly urgent.

### libsigsegv replacement:

- this PR includes a custom SEH handler to replace our use of libsigsegv, resulting in massive performance improvements

before:

```
> :time =|(i=@ud |-(?:(=(i 0xff.ffff) ~ $(i +(i)))))
>=
[%took ~s5..c229]
> :time =|(i=@ud |-(?:(=(i 0xff.ffff) ~ $(i +(i)))))
>=
[%took ~s2..d5c8]

> :time (gulf 1 0xf.ffff)
>=
[%took ~s5..0cac]
> :time (gulf 1 0xf.ffff)
>=
[%took ~s0..8a08]

> :time (jam (gulf 1 0xf.ffff))
>=
[%took ~s29..9843]
> :time (jam (gulf 1 0xf.ffff))
>=
[%took ~s2..d245]

> :time (cue (jam (gulf 1 0xf.ffff)))
>=
[%took ~s38..d209]
> :time (cue (jam (gulf 1 0xf.ffff)))
>=
[%took ~s5..7cdf]
```

after:

```
> :time =|(i=@ud |-(?:(=(i 0xff.ffff) ~ $(i +(i)))))
>=
[%took ~s3..0489]
> :time =|(i=@ud |-(?:(=(i 0xff.ffff) ~ $(i +(i)))))
>=
[%took ~s2..fb4a]

> :time (gulf 1 0xf.ffff)
>=
[%took ~s0..af85]
> :time (gulf 1 0xf.ffff)
>=
[%took ~s0..9e9e]

> :time (jam (gulf 1 0xf.ffff))
>=
[%took ~s2..fbbc]
> :time (jam (gulf 1 0xf.ffff))
>=
[%took ~s2..d823]

> :time (cue (jam (gulf 1 0xf.ffff)))
>=
[%took ~s5..c382]
> :time (cue (jam (gulf 1 0xf.ffff)))
>=
[%took ~s5..a927]
```

(each expression was timed twice in a new process, the first time includes the cost of page-faults. note also that `:time` is a low-resolution benchmark of wall-clock time ...)

--------

Barring the minor improvements requested above, I think this PR is ready to be merged. The biggest obstacle to integration will be the coming terminal rewrite (#4463). I tried a merge locally, and the conflicts look quite manageable. But it's possible that there will be issues with new functionality (2-dimensional output / screen updates, log/slog handling). /cc @Fang-

2021-06-04 13:28 UTC, locpyl-tidnyd commented on nix/sources-mingw.json
> +}
Fixed.

2021-06-04 13:28 UTC, locpyl-tidnyd commented on pkg/urbit/compat/mingw/compat.h
> +#endif//_MINGW_IO_H
Fixed.

2021-06-04 13:31 UTC, locpyl-tidnyd commented on .github/workflows/build.yml
> +          CACHIX_CACHE: locpyl-tidnyd-test1
Please do this when merging, as I am using this temporary cache while I'm still working on the PR.

2021-06-04 13:32 UTC, locpyl-tidnyd commented on pkg/ent/configure
>      export IMPL=$impl
Added `.gitignore` lines in 839a68e.

2021-06-04 13:33 UTC, locpyl-tidnyd commented on pkg/urbit/compat/mingw/argon2u.patch
> +
3559394 updates the argon2u dependency and removes the patch.

2021-06-04 13:35 UTC, locpyl-tidnyd commented on pkg/urbit/compat/mingw/seh_handler_decorator.mk
> +CCEXTRA  = -E -o -|$(sehdexe) $<|$(CC) $(CFLAGS) -x cpp-output -
4ecfb14 comments what is happening. `-x cpp-output` tells `$(CC)` to treat its standard input as preprocessor output, as it cannot deduce this from the input filename.

2021-06-04 13:40 UTC, locpyl-tidnyd commented on pkg/urbit/compat/mingw/seh_handler_decorator.cc
> +}
Yes. I have added [some comments](https://github.com/urbit/urbit/blob/4ecfb14cbfbbc6cd6d0ac2180298cb2ce5a82ff4/pkg/urbit/compat/mingw/seh_handler_decorator.mk) about both the build process and the technique in commit 4ecfb14:
```
# This include file injects a step that transforms vere C source to register
# a SEH exception handler for each function that is declared in a .c file.
# It inserts a .seh_handler directive into each function body with __asm__.
# This directive affects the x64 unwind tables (.pdata and .xdata sections)
# emitted by the compiler.
#
# See gas/config/obj-coff-seh.h in binutils source for .seh_handler, and
# https://docs.microsoft.com/en-us/cpp/build/exception-handling-x64
# for a description of how stack unwinding and SEH work in x64 Windows.
```

2021-06-04 13:54 UTC, locpyl-tidnyd commented
Ctrl-Break is the "ungraceful exit" key in Windows console. Windows uses `^Z` as the end-of-file character where Unix uses `^D`.

2021-06-04 14:40 UTC, locpyl-tidnyd commented on pkg/urbit/compat/mingw/poor-mans-nix-shell.sh
> +    dir=../$hash-$key
f869bd1 does this.

2021-06-04 14:42 UTC, locpyl-tidnyd commented on pkg/urbit/Makefile
> +	@$(CC) -I./include $(CFLAGS) $< $(CCEXTRA) -c -o $@
Added a comment in 4ecfb14.

2021-06-04 17:56 UTC, joemfb approved these changes
LGTM

2021-06-04 19:37 UTC, locpyl-tidnyd reviewed
Commit message fail: should have been "put downloaded dependencies under $NIX_STORE (defaults to ...)"

2021-09-09 14:09 UTC, merged