npm: Updated http-api and api packages
urbit/urbit pull request #4810
Opened 2021-04-22 14:20 UTC by tylershuster

This brings the `@urbit/api` and `@urbit/http-api` code in the code base up to date with what is currently published on npm. 

Landscape does not rely on `http-api` so those changes shouldn't be a problem — most of these changes are bugifxes discovered while working on https://github.com/urbit/urbit/pull/4611 or by other contributors.

Landscape does rely on `api` but most of those changes should be to functions that have not been integrated back into Landscape yet.

2021-04-22 14:21 UTC, tylershuster commented
Generally, I want to unblock other work that relies on this to make the eventual migration to `http-api` easier.

2021-04-26 23:02 UTC, liam-fitzgerald requested changes
One type error, looks good otherwise

2021-04-26 23:36 UTC, tylershuster commented on pkg/npm/api/metadata/types.ts
> +  config: { graph: string };
as in:

```ts
config: {
  graph?: string;
  group?: {} | Resource;
}
```

2021-04-28 21:04 UTC, tylershuster commented on pkg/npm/api/metadata/types.ts
> +  config: { graph: string };
@liam-fitzgerald ?

2021-05-03 23:06 UTC, liam-fitzgerald commented on pkg/npm/api/metadata/types.ts
> +  config: { graph: string };
no:
```typescript
interface Metadata {
// elided
  config: MetadataConfig;
}

type MetadataConfig = GroupConfig | GraphConfig;
interface GroupConfig {
  group: null | {} | Resource;
}
interface GraphConfig {
  graph: string;
}
```
```

2021-05-05 00:06 UTC, tylershuster commented
Ok, then this looks g2g

2021-05-05 00:31 UTC, matildepark approved these changes

2021-05-05 00:31 UTC, liam-fitzgerald approved these changes

2021-05-05 00:31 UTC, merged