interface: adding basic notifications
urbit/urbit pull request #4873
Opened 2021-05-06 23:24 UTC by tylershuster

dumb, works.

<img width="936" alt="image" src="https://user-images.githubusercontent.com/3999320/117377152-6f890200-ae87-11eb-8531-b6ed8f95ef70.png">

Button only shows if they're not allowed. Use the browser's UI to disable them

2021-05-06 23:30 UTC, tylershuster commented
@liam-fitzgerald Can you tell me offhand to get the reference of the notification? All the hark updates are...ill-documented

2021-05-07 01:00 UTC, liam-fitzgerald requested changes

2021-05-07 01:00 UTC, liam-fitzgerald commented on pkg/interface/src/logic/reducers/hark-update.ts
> +        tag: 'landscape',
? This will notify on literally every message lol. Move this logic to 'add-note'

2021-05-13 17:10 UTC, matildepark approved these changes
Sure is basic notifications!

2021-05-13 17:10 UTC, merged