arvo/hoon: add +sloy, a %da short-circuited +slay to speed up +de-beam and thus +look
urbit/urbit pull request #4932
Opened 2021-05-24 00:49 UTC by tacryt-socryp

2021-05-26 18:01 UTC, joemfb requested changes

2021-05-26 18:31 UTC, tacryt-socryp commented on pkg/arvo/sys/arvo.hoon
> +  ?~  ved=(sloy i.t.t.p)  ~
This looks like a good approach to me. I'll break it out into its own `+de-case` arm for clarity.

2021-05-26 20:54 UTC, tacryt-socryp commented on pkg/arvo/sys/arvo.hoon
> +  ?~  ved=(sloy i.t.t.p)  ~
Done and tested. All good, maybe marginally faster.

2021-05-26 21:29 UTC, joemfb requested changes

2021-05-26 21:29 UTC, joemfb commented on pkg/arvo/sys/arvo.hoon
> +  ~/  %en-case
Please rename to `+de-case`. `+en-case` would be `|=(=case (scot case))`, if you wanted it.

2021-05-26 22:36 UTC, joemfb requested changes
This looks great -- a couple nits:

2021-05-26 22:36 UTC, joemfb commented on pkg/arvo/sys/arvo.hoon
> +  `(unit beam)`[~ [`ship`u.who `desk`u.des `case`u.ved] t.t.t.p]
It looks like there are extra casts in this line, it'd be nice to clean it up. I think only `ship` and `desk` should be necessary:

```
`[[`ship`u.who `desk`u.des u.ved] t.t.t.p]
```

2021-05-26 22:36 UTC, joemfb commented on pkg/arvo/sys/arvo.hoon
> +  ~/  %en-case
This hint should be `%de-case` as well.

2021-05-26 23:01 UTC, joemfb approved these changes
LGTM

2021-05-27 19:21 UTC, joemfb commented
This PR should target `release/next-sys`

2021-06-01 18:45 UTC, merged