btc: use blockfilter when requesting address info
urbit/urbit pull request #5005
Opened 2021-06-11 23:15 UTC by ixv

Now when we get updated about a new block, only request address info for addresses that match that block's blockfilter. If there's a gap of multiple blocks, we need to go request blockfilter information for those blocks specificially. 

This depends on this PR on the urbit-bitcoin-rpc repo, which allows you to make those requests for specific block information: https://github.com/timlucmiptev/urbit-bitcoin-rpc/pull/26

2021-06-15 07:20 UTC, timlucmiptev commented
Looks good, just two comments/questions:

1. Do we want to expose bip158 via bitcoin.hoon? I split up the various BIP functionality just for modularity, but it doesn't seem like a relevant detail to app developers.

2. Do you want to have a `gap` size past which you just check addresses in the normal way? If a wallet was offline a long time and missed tons of blocks, the fetching of blockfilters would take longer than just checking addresses, since blockfilters aren't *that* small (~10% of total block size iirc).

2021-06-15 07:28 UTC, ixv commented
1. Not sure I understand, do you mean doing `/+  bip-b158` in `/lib/bitcoin.hoon` rather than in  `/app/btc-wallet.hoon`, or did you have something else in mind?

2. Yeah that's a good idea, what would you suggest is a good gap size?

2021-06-15 09:24 UTC, timlucmiptev commented
1. Yeah, include it in `lib/bitcoin.hoon`. If we only use 1 or 2 of its functions externally (I think that's the case?), you could even wrap just those in arms, which seems best now that I think about it.

2. I just checked the blockfilter for the latest block: it was ~32K bytes on a 1.5M block, so about 2% of the size. In terms of what we're good sending over Ames, I think about 50 blocks would be good here? 1.5M on a reconnect seems reasonable, but if you feel it's too much, use that ~30KB number to adjust as appropriate.

2021-06-17 10:51 UTC, timlucmiptev commented
If `all-match` is the only thing we use externally from BIP158, I would only expose that and `match` as public arms through `bitcoin.hoon`.

Other than that, looks good. Might want a review from @tacryt-socryp  on the provider kick/re-sub.

2021-06-17 15:37 UTC, tacryt-socryp requested changes
I don't see anything here to handle a negative watch ack. We want to ensure we don't cause a resubscribe loop in that case. Otherwise, small style nits

2021-06-17 15:37 UTC, tacryt-socryp commented on pkg/arvo/app/btc-wallet.hoon
> +    ;:  weld  cards
Use regular form with %+ when only using two items.

2021-06-17 15:37 UTC, tacryt-socryp commented on pkg/arvo/app/btc-wallet.hoon
> +    ;:  weld  cards
Regular form

2021-06-17 15:37 UTC, tacryt-socryp commented on pkg/arvo/app/btc-wallet.hoon
> +  ?.  =(network network:(~(got by walts) xpub))  ~
Crashing here in the got by seems like a bad idea. Let's make sure we produce ~ instead

2021-06-17 21:52 UTC, ixv commented
Not sure I follow, if we don't want to do anything in the negative watch-ack case, why isn't the default-agent handling of this sufficient?

2021-06-17 22:22 UTC, tacryt-socryp commented
Line 729 won't compile due to using a gap inside of the (weld ... ) statement. As for the watch nack, I think you're right, but we need a more semantic error message for the crash, likely with a `~|`

2021-06-17 22:54 UTC, ixv commented
Alright done, also found and fixed another issue with it

2021-06-18 00:35 UTC, tacryt-socryp approved these changes

2021-06-18 04:29 UTC, merged