interface: form handling, optimism sweep
urbit/urbit pull request #5115
Opened 2021-07-19 05:02 UTC by liam-fitzgerald

- Fixes ColorInput text entry case
- Makes DM settings optimistic, removes submission button
- Changes ImageInput to not set the form error on upload failure, instead setting its own error variable
- Fixes CalmEngine pulling incorrect prop from form
- Unifies optimistic state handling for forms

The one true way ™ to do optimistic form inputs now is to do the following
- Ensure that you're hooking into optimistic state updates inside the onSubmit, and select the initialValues directly from state (i.e. the selector that you pass the hook should return initialValues directly
- use formikOnBlur
- done!

2021-07-19 21:56 UTC, matildepark requested changes
Ignores colour picker

![Jul-19-2021 17-56-06](https://user-images.githubusercontent.com/20846414/126232561-a2ac453a-2068-4418-91ce-a3ccc82e00b0.gif)

2021-07-20 18:06 UTC, arthyn approved these changes
Curious what you think about the poke changes, but everything looks good

2021-07-22 04:23 UTC, liam-fitzgerald commented on pkg/interface/src/views/apps/settings/components/lib/GroupChannelPicker.tsx
> +  const [{ value }, , { setValue, setTouched }] = useField(
This is actually not our api, it's formik's

2021-07-22 04:24 UTC, liam-fitzgerald commented on pkg/interface/src/views/components/FormikOnBlur.tsx
> +      formikBag.submitForm();
No, it's because the newly introduced debounce prevents double submission

2021-07-22 04:24 UTC, liam-fitzgerald commented on pkg/interface/src/logic/state/hark.ts
> +      const poke = setMentions(mentions);
No it's a terrific point, i'll change the added ones here, and we can maybe move to this pattern

2021-07-22 16:33 UTC, matildepark approved these changes

2021-07-22 16:33 UTC, merged

2021-07-22 20:32 UTC, arthyn commented on pkg/interface/src/views/apps/settings/components/lib/GroupChannelPicker.tsx
> +  const [{ value }, , { setValue, setTouched }] = useField(
oh derp, thanks