eyre: restart subscriptions faster
urbit/urbit pull request #5132
Opened 2021-07-26 04:44 UTC by liam-fitzgerald

Stores the precomputed JSON in the channel event fact, instead of
converting it twice. This removes clamming and conversion from the
hot path of reestablishing a channel. Roughly a 10x speedup in 
re-opening channels.

2021-07-26 19:22 UTC, Fang- reviewed
Any reason we're not doing a full revert of 7e5f29c and going back to doing `%watch-as %json` subscriptions?

For the record, keeping json blobs around is probably fine now due to Eyre's "clogging" mechanism (#3749) killing subscriptions that accrue too many unacked events. The heuristic for determining what's "too many" there is still open to being fine-tuned.

2021-07-26 19:22 UTC, Fang- commented on pkg/arvo/sys/vane/eyre.hoon
>        ::  connected, we *will* send it immediately.
This comment (incl. the line above what I could select here) should probably be removed.

2021-07-26 19:22 UTC, Fang- commented on pkg/arvo/sys/vane/eyre.hoon
> +    ::  +channel-event-to-json: render chanel event from request-id as json
```suggestion
    ::  +channel-event-to-json: render channel event from request-id as json
```

2021-07-26 19:22 UTC, Fang- commented on pkg/arvo/sys/vane/eyre.hoon
> +      ::
No we don't anymore!

2021-07-26 20:28 UTC, tacryt-socryp approved these changes
This looks sane to me and leaves the other logic in place. The space tradeoff seems worth it, particularly given that we can tweak the subscription kill algorithm for more savings if needed.

2021-08-30 03:28 UTC, liam-fitzgerald commented on pkg/arvo/sys/vane/eyre.hoon
> +  --
`$channel` & `$channel-state` have changed, because `$channel-state` contains `$channel-event` and `$channel` contains `$channel-state`

2021-08-30 03:42 UTC, tacryt-socryp requested changes

2021-08-30 03:42 UTC, tacryt-socryp commented on pkg/arvo/sys/vane/eyre.hoon
> +
Get rid of newline

2021-08-31 12:36 UTC, Fang- approved these changes
Changes look good to me, thanks!

2022-07-03 13:18 UTC, tacryt-socryp commented
Ping.

2022-07-06 22:36 UTC, liam-fitzgerald commented
Discussed out of band with @Fang-, closing for the following reasons:
- This aggravates the already intense memory pressure issues that occur on the network, due to lack of noun deduplication
- It conflicts quite severely with https://github.com/urbit/urbit/pull/5877, which is clearly the best path forward for this channel interface.

2022-07-06 22:36 UTC, closed without merging