ames-flow-kill
urbit/urbit pull request #5191
Opened 2021-08-29 19:52 UTC by h5gq3

2021-08-31 14:57 UTC, belisarius222 requested changes
Thanks for making this PR!

Initial review, just a bunch of style nitpicking.  Will review more thoroughly after cleanup.

2021-08-31 14:57 UTC, belisarius222 commented on pkg/arvo/sys/vane/ames.hoon
> +    ::  client vane cork task -> client ames pass cork as plea -> server ames sinks plea -> server ames +on-plea (we are here)
80 characters

2021-08-31 14:57 UTC, belisarius222 commented on pkg/arvo/sys/vane/ames.hoon
> +      abet:(on-memo:(make-peer-core peer-state channel) bone plea %plea)
de-indent this line

2021-08-31 14:57 UTC, belisarius222 commented on pkg/arvo/sys/vane/ames.hoon
> +        =.  by-duct.ossuary.peer-state  (~(del by by-duct.ossuary.peer-state) (got-duct bone))
past 80 characters, I think

2021-08-31 14:57 UTC, belisarius222 commented on pkg/arvo/sys/vane/ames.hoon
> +          peer-core
de-indent

2021-08-31 14:57 UTC, belisarius222 commented on pkg/arvo/sys/vane/ames.hoon
> +          (send-shut-packet bone [message-num %& +]:f)
de-indent

2021-08-31 14:57 UTC, belisarius222 commented on pkg/arvo/sys/vane/ames.hoon
> +      :: resetting timer for boons
multiple indentation problems in this arm

2021-08-31 14:57 UTC, belisarius222 commented on pkg/arvo/sys/vane/ames.hoon
> +        ?:  |((~(has in closing.peer-state) bone) (~(has in corked.peer-state) bone))  peer-core
past 80 characters: this line, and the later conditionals that look similar

2021-08-31 14:57 UTC, belisarius222 commented on pkg/arvo/sys/vane/ames.hoon
> +          =?  closing.peer-state  ?=([%cork *] payload.plea)  (~(put in closing.peer-state) bone)
past 80

2021-08-31 14:57 UTC, belisarius222 commented on pkg/arvo/sys/vane/ames.hoon
> +  --
indent

2021-08-31 14:57 UTC, belisarius222 commented on pkg/arvo/sys/vane/ames.hoon
> +    =?  message-sink  !cork  (give %send message-num %| ok %| lag=`@dr`0)
I think these three lines can be replaced by two:
```
=.  message-sink  (give %send message-num %| ok cork lag=`@dr`0)
=?  message-sink  cork  (give %cork ~)
```

2021-08-31 14:57 UTC, belisarius222 commented on pkg/arvo/sys/vane/gall.hoon
> +    =.  mo-core  (mo-pass wire note-arvo)
indent

2021-09-01 15:35 UTC, h5gq3 commented
fixed styling.
but the whole thing doesn't build. is this because this PR is not yet finished?

2022-08-24 17:44 UTC, joemfb commented
This was included in #5644, which was included in #5886 and just released.

2022-08-24 17:44 UTC, closed without merging