grid: real ship display
urbit/urbit pull request #5201
Opened 2021-09-04 01:21 UTC by arthyn

This pulls over contact store from current Landscape and adds a new component for rendering sigils/avatars.

Two issues currently, there's a bad module ref in urbit/sigil-js that needs to be resolved looks like a mis-paste. Second there's some eslint issues with some of the contact store code. Other than that seems to work on mock data and testnet.

2021-09-05 22:27 UTC, liam-fitzgerald requested changes
LGTM! I'll make these changes bc you're out this week

2021-09-05 22:27 UTC, liam-fitzgerald commented on pkg/grid/src/nav/search/Providers.tsx
>      [allies, search]
Missing contacts as a dep

2021-09-08 05:45 UTC, liam-fitzgerald approved these changes

2021-09-08 05:46 UTC, liam-fitzgerald commented
Blocked on design feedback and also of new release of `@tlon/sigil-js` cc: @urcades @g-a-v-i-n

2021-09-08 12:28 UTC, urcades commented
For an issue like this it might hasten review time if we could get a screenshot of the (presumably) single place sigils/avatars are displayed — right now I'm running into build issues and can't seem to get `esbuild` related errors to go away after following the error debugging prompts:

```
failed to load config from /Users/ed/Urbit Projects/urbit/pkg/grid/vite.config.ts
error when starting dev server:
Error: The service was stopped
    at /Users/ed/Urbit Projects/urbit/pkg/grid/node_modules/esbuild/lib/main.js:1215:25
    at /Users/ed/Urbit Projects/urbit/pkg/grid/node_modules/esbuild/lib/main.js:609:9
    at Socket.afterClose (/Users/ed/Urbit Projects/urbit/pkg/grid/node_modules/esbuild/lib/main.js:587:7)
    at Socket.emit (node:events:406:35)
    at Socket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

2021-09-08 12:39 UTC, urcades commented
making some progress here after trying to reset package-lock and node_modules:

```
 > src/components/Avatar.tsx:3:37: error: [plugin: vite:dep-scan] Failed to resolve entry for package "@tlon/sigil-js". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@tlon/sigil-js". The package may have incorrect main/module/exports specified in its package.json.
 ```

and this, which follows:

```
error when starting dev server:
Error: Build failed with 1 error:
src/components/Avatar.tsx:3:37: error: [plugin: vite:dep-scan] Failed to resolve entry for package "@tlon/sigil-js". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@tlon/sigil-js". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (/Users/ed/Urbit Projects/urbit/pkg/grid/node_modules/esbuild/lib/main.js:1451:15)
    at /Users/ed/Urbit Projects/urbit/pkg/grid/node_modules/esbuild/lib/main.js:1131:28
    at runOnEndCallbacks (/Users/ed/Urbit Projects/urbit/pkg/grid/node_modules/esbuild/lib/main.js:921:63)
    at buildResponseToResult (/Users/ed/Urbit Projects/urbit/pkg/grid/node_modules/esbuild/lib/main.js:1129:7)
    at /Users/ed/Urbit Projects/urbit/pkg/grid/node_modules/esbuild/lib/main.js:1238:14
    at /Users/ed/Urbit Projects/urbit/pkg/grid/node_modules/esbuild/lib/main.js:609:9
    at handleIncomingPacket (/Users/ed/Urbit Projects/urbit/pkg/grid/node_modules/esbuild/lib/main.js:706:9)
    at Socket.readFromStdout (/Users/ed/Urbit Projects/urbit/pkg/grid/node_modules/esbuild/lib/main.js:576:7)
    at Socket.emit (node:events:394:28)
    at Socket.emit (node:domain:475:12)
```

2021-09-08 15:09 UTC, g-a-v-i-n commented
I published @tlon/sigil-js 1.4.4 which
    * Corrects typo in package.json
    * Updates react dep to ^17

Hope that helps

2021-09-08 15:47 UTC, g-a-v-i-n commented
And yes, screen shots would be greatly appreciated

2021-09-08 16:36 UTC, g-a-v-i-n approved these changes

2021-09-08 23:28 UTC, merged