http-api: add method to try to initialize from existing cookie
urbit/urbit pull request #5202
Opened 2021-09-04 19:39 UTC by eamsden

(and session.js context)

(draft because not yet tested, would appreciate style/architecture comments)

Provides a static method to initialize an `Urbit` airlock object based on the existing session cookies in a browser, and the `window.ship` property set by the dynamically generated `session.js`, thus allowing applications using the HTTP api to avoid
requiring a separate login step when loaded from a ship in an existing browser session.

It is intended that browser applications using react will add a static script tag

```html
<script src="/~landscape/js/session.js"></script>
```

This mechanism is currently used by the bitcoin wallet and Landscape to dynamically determine the ship name. 
An application which includes this script tag will then be able to invoke `await Urbit.tryExistingSession()` to receive an airlock object, which will connect to the `window.location.origin` as the base URL for the airlock. If either of the necessary properties (`window.location.origin` and `window.ship`) are undefined, or the context is not a browser, or if the initialization of the event source throws an exception, then `Urbit.tryExistingSession()` will throw an exception.

2021-09-05 22:16 UTC, liam-fitzgerald commented on pkg/npm/http-api/src/Urbit.ts
> +    const airlock = new Urbit(window.location.origin);
can just be `const airlock = new Urbit('');` and also remove the origin check

2021-09-05 22:17 UTC, liam-fitzgerald commented on pkg/npm/http-api/src/Urbit.ts
> +  /** This is basic interpolation to get the cpokehannel URL of an instantiated Urbit connection. */
????

2021-09-05 22:17 UTC, liam-fitzgerald requested changes
Looks good other than typo and URL injection

2021-09-06 01:10 UTC, eamsden commented on pkg/npm/http-api/src/Urbit.ts
> +  /** This is basic interpolation to get the cpokehannel URL of an instantiated Urbit connection. */
woops, accidental vim

2021-09-07 13:21 UTC, eamsden commented
Closing in favor of some documentation that points out:
- no need to start the event source explicitly, it will be done by the first poke or subscribe
- an empty string for the URL results in channel URLs being host-relative.
- you can simply set ship from window.ship

So this is sufficient initialization code:
```javascript
const airlock = new Urbit('', '');
airlock.ship = window.ship;
```

2021-09-07 13:21 UTC, closed without merging