boot: bring your own boot sequence
urbit/urbit pull request #5470
Opened 2021-12-03 23:47 UTC by Fang-

Technically more like, "add your own boot sequence events".

This implements a set of boot arguments starting with `--prop-`, used for loading in "props", jamfiles that contain additional events for inclusion in the boot sequence. (The dream is to make this just be a single `--prop` or w/e that auto-distinguishes between filepaths, urls and names, but we're grounded in reality for now.)

Intended use cases here include specifying desks to install during boot, bootstrapping Azimuth state, custom userspace configuration, etc. Being able to do these separate from the pill brings some much-needed flexibility and lets us eradicate "multi-pills" from existence.

Main thing to look at is the definition of `$prop` in base-dev's `/lib/pill` and the way those nouns get handled in `mars.c`.

Based on and targeting `jb/wip-urth` for @joemfb's convenience.  
Includes #5428 because we want long opts for this.  
Includes #5389 because that should be updated to make use of the affordances this provides. Draft mode until `/app/autopill` improvements make their way in, but the vere part here should be ready for its first review.

2021-12-16 16:41 UTC, Fang- commented
This now includes an updated `pkg/autoprop` for auto-generating pill and prop files. Thanks to both @joemfb and @philipcmonk for the clay pointers. Please take a look, this should be ready for full review now.

2022-01-26 18:30 UTC, joemfb requested changes
Sorry for the absurd delay @Fang-!

This all looks reasonable. I've picked some nits the C changes, and noted a couple refcounting issues. I've only minimally reviewed the hoon so far, mostly to highlight some questions about the new move/message types that have been introduced.

We'll need to go over which ovums are included in the pill by default, and which (if any) props are downloaded by default. I suspect will want a set of default URL props, and a commandline flag to turn them off.

2022-01-26 18:30 UTC, joemfb commented on pkg/urbit/worker/mars.c
> +        }
This seems redundant and wrong, did the format change somehow?

2022-01-26 18:30 UTC, joemfb commented on pkg/urbit/worker/mars.c
> +            aft = u3kb_weld(aft, ves);
`u3k(ves)`

2022-01-26 18:30 UTC, joemfb commented on pkg/urbit/worker/mars.c
> +
this should all be in its own block (starting with `u3_noun mos = mor;`), and it should end with `u3z(mor)` (which is being leaked).

2022-01-26 18:30 UTC, joemfb commented on pkg/base-dev/lib/pill.hoon
> +  +$  tier  ?(%pre-userspace %post-userspace)
I'm tempted to say that these types should be in the kernel somewhere. They are being referenced in the ipc boot message specification. But I'm not sure where.

I don't like the aesthetic of `$tier`, I'd rather it be something like `?(%fore %hind)`. And I'm having trouble coming up with a use-case for other tiers ("pre-kernelspace"?). Thoughts?

2022-02-08 22:40 UTC, Fang- commented on pkg/urbit/vere/king.c
> +        }
I added some dumb retry logic. Not sure what else you were imagining with better error handling here. Probably not worth following redirects or w/e?

2022-02-08 22:40 UTC, Fang- commented on pkg/arvo/sys/lull.hoon
> +        [%prep lat=(map lobe blob)]                     ::  prime blob store
Discussed this with @philipcmonk, just leaving it as a `map` for now.

2022-02-09 23:41 UTC, Fang- commented on pkg/urbit/daemon/main.c
> +      "https://bootstrap.urbit.org/props/brass.pill";
@joemfb This change probably won't pass muster. Not sure what the correct solution here is though.

I have deployed the version of `/app/autoprop` from this PR to a ~zod moon, running next to a little script that uploads the .pill and .jam files it generates to bootstrap.urbit.org, using static per-prop filenames.

We could have the autoprop build pills with the old versioned naming scheme, but then need to be very good about remembering to update the autoprop config whenever necessary. The point of this side of this work is to have automated nearly-latest pills... Arguably if you find yourself trying to use a pill you can't run, you shouldn't be using this old a binary anyway?

2022-04-01 14:28 UTC, joemfb approved these changes
There's a couple things here I may still want to tweak, especially the behavior around default props. But I'm going to merge this out of band (don't worry about the conflicts), so I'll address those elsewhere.

Thanks for pulling this together!

2022-04-01 14:28 UTC, merged