build: remove urbit-king haskell releases and haskell.nix dependency
urbit/urbit pull request #5478
Opened 2021-12-08 09:11 UTC by brendanhay

* Upgrades the nixpkgs pin to 21.11.
* Removes nix code, sources, and attributes related to haskell.nix and  the code under pkg/hs.
* Continuous integration no longer builds (or packages/tarballs/releases) urbit-king (haskell).
* To continue to developing any haskell code under pkg/hs it's left as  a user exercise uto install and configure GHC/Stack.
* Fixes some minor issues like overriding the existing `curlMinimal` attribute in `overlays/native.nix` causing unnecessary rebuilds.

As a consequence running nix-shell should be considerably more performant and requires downloading or building less dependencies. CI also has less work to do in general.

2021-12-09 08:01 UTC, joemfb requested changes
This all looks reasonable. I'm not sure what's going wrong with the docker image ... (/cc @eamsden).

a secp nit:

2021-12-09 08:05 UTC, joemfb commented
Also, this works on my machine without nixpkgs version patches, which is pretty nice. This PR supersedes #5165.

2021-12-09 08:06 UTC, brendanhay commented
> Also, this works on my machine without nixpkgs version patches, which is pretty nice. This PR supersedes #5165.

Imagine if we updated nixpkgs more than once per year!

2021-12-09 08:55 UTC, mrdomino commented
went ahead and added schnorr signatures to the pmnsh secp256k1 build. If desired, can drop that and put it in separately.

LGTM

2021-12-09 08:56 UTC, mrdomino approved these changes

2021-12-09 08:57 UTC, mrdomino commented
\> it failed

that's embarrassing. out-of-date commit. will fix.

2021-12-09 09:03 UTC, mrdomino commented
i just force-pushed my commits out of your PR, sorry, i'll go and sort them out on my own.

2021-12-09 09:11 UTC, brendanhay commented on nix/sources.json
> +        "url": "https://github.com/bitcoin-core/secp256k1/archive/26de4dfeb1f1436dae1fcf17f57bdaa43540f940.tar.gz",
Updated PTAL

2021-12-09 09:18 UTC, mrdomino commented
Made a PR against your PR: #5483

2021-12-18 04:36 UTC, joemfb approved these changes
LGTM

2021-12-18 04:36 UTC, merged