groups: fix rejoining a group after an error
urbit/urbit pull request #5576
Opened 2022-01-31 22:28 UTC by liam-fitzgerald

Fixes some edge cases in %group-view that would previously require a `|nuke %group-view` 

Additionally provides further interactivity if a group joining case fails. 
- Retry will simply attempt to rejoin the group
- Abort will remove the "Join Failed" tile and remove any persisted attempt, closing the window

<img width="392" alt="Screen Shot 2022-01-31 at 4 24 15 pm" src="https://user-images.githubusercontent.com/46801558/151883211-37376c48-46fe-4a52-9c9d-dfc9bf49fc9b.png">
<img width="160" alt="Screen Shot 2022-01-31 at 4 24 20 pm" src="https://user-images.githubusercontent.com/46801558/151883214-9b9e7d53-1f92-4e4f-9449-2eb3e5e1e039.png">

2022-01-31 23:04 UTC, arthyn requested changes
Just a few small things otherwise looks good

2022-01-31 23:16 UTC, liam-fitzgerald commented on pkg/interface/src/views/landscape/components/Join/Join.tsx
> +    useGroupState.getState().abortJoin(desc.group);
none that I can think of off the top of my head

2022-02-01 17:05 UTC, liam-fitzgerald commented on pkg/interface/src/views/apps/launch/App.tsx
> +                onClick={() => history.push({ search: "?join-kind=groups" })}
can't find that function in this checkout of `next/groups`?

2022-02-02 18:29 UTC, arthyn commented on pkg/interface/src/views/apps/launch/App.tsx
> +                onClick={() => history.push({ search: "?join-kind=groups" })}
Ah master probably needs to be merged into next/groups, sorry

2022-02-03 16:48 UTC, arthyn commented on pkg/interface/src/views/apps/launch/App.tsx
> +                onClick={() => history.push({ search: "?join-kind=groups" })}
Alright I just merged master into next/groups if you want to pull it in

2022-02-03 17:13 UTC, liam-fitzgerald commented on pkg/interface/src/views/apps/launch/App.tsx
> +                onClick={() => history.push({ search: "?join-kind=groups" })}
done

2022-02-03 17:20 UTC, arthyn approved these changes

2022-02-03 20:27 UTC, merged

2022-02-24 19:51 UTC, nerveharp commented
Fixes urbit/landscape#1389