arvo: language-server desk support
urbit/urbit pull request #5628
Opened 2022-03-06 20:46 UTC by ryjm

Looks in all desks when attempting to build a file and picks the first match.

2022-03-07 19:02 UTC, liam-fitzgerald requested changes
Some nits, general idea looks good. Wondering if you have any ideas for the direction of cross-desk support in the LSP?

2022-03-07 19:02 UTC, liam-fitzgerald commented on pkg/arvo/app/language-server.hoon
> +    /commit˘
???

2022-03-07 19:02 UTC, liam-fitzgerald commented on pkg/arvo/app/language-server.hoon
> +  =/  bek  byk.bow
This will have the wrong case, you'll want
```hoon
=/  bek  byk.bow(r da+now.bow)
```

2022-03-08 12:19 UTC, ryjm commented on pkg/arvo/app/language-server.hoon
> +    /commit˘
what it's cute

2022-03-08 19:04 UTC, liam-fitzgerald approved these changes

2022-03-08 19:06 UTC, merged