groups/grid: Move security from groups to grid
urbit/urbit pull request #5630
Opened 2022-03-08 18:51 UTC by patosullivan

For: https://github.com/urbit/landscape/issues/1186

Moves logout of session(s) functionality from groups into grid's system preferences:

![image](https://user-images.githubusercontent.com/1221094/157305067-be059c27-4510-4132-a869-31ed50ed90d5.png)

Used existing landscape lock icon for the menu icon. Added radix-ui's checkbox package (and icons package for their check icon) to build out the checkbox in grid.

2022-03-08 19:00 UTC, liam-fitzgerald commented
- This should be split into to two PRs, one for landscape and one for groups
- wtf is going on with package-lock.json? cc: @arthyn 

Looks good otherwise

2022-03-08 19:00 UTC, liam-fitzgerald commented
Also, CI is borked

2022-03-08 19:23 UTC, patosullivan commented
> Also, CI is borked

CI should be fixed now, forgot to delete an import.

2022-03-08 19:23 UTC, patosullivan commented
> * This should be split into to two PRs, one for landscape and one for groups
> * wtf is going on with package-lock.json? cc: @arthyn
> 
> Looks good otherwise

Talked with @arthyn earlier, re: two PRs, he suggested we could just do it all in one

2022-03-08 20:24 UTC, liam-fitzgerald commented
@arthyn how does this get released in lockstep?

2022-03-08 20:42 UTC, arthyn commented
@liam-fitzgerald I think it'd be safe to release to landscape first and then groups second maybe separated by a day

2022-03-08 20:43 UTC, liam-fitzgerald commented
Alright sounds good to me


On Tue, Mar 08, 2022 at 14:42:56, Hunter Miller ***@***.***>
wrote:

> @liam-fitzgerald <https://github.com/liam-fitzgerald> I think it'd be
> safe to release to landscape first and then groups second maybe separated
> by a day
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/urbit/urbit/pull/5630#issuecomment-1062189862>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALFCFFS77JVPTZPAO4UR23DU663VBANCNFSM5QHGGEMQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-08 21:25 UTC, arthyn requested changes
Looks good, just some minor changes. We should probably consider moving away from icons library to our own when we start building out new indigo.

2022-03-08 21:25 UTC, arthyn commented on pkg/grid/src/components/Checkbox.tsx
> +        // style={{ width: 28, height: 28 }}
```suggestion
```

2022-03-08 21:25 UTC, arthyn commented on pkg/grid/src/components/icons/Lock.tsx
> +      fill="black"
Probably should rip out fill here and replace with className="fill-current" so that it will be open to other colors

2022-03-09 17:37 UTC, patosullivan commented
@arthyn, I made the requested changes

2022-03-09 17:43 UTC, arthyn approved these changes

2022-03-09 17:46 UTC, merged