c3: add file path module for easy path manipulation
urbit/urbit pull request #5642
Opened 2022-03-16 20:57 UTC by mcevoypeter

Add `c3_path` type for easily creating and manipulating file paths. We currently use `snprintf` in many places to build up file paths, which is at best a hassle and at worst prone to buffer overflow bugs. The `c3_path` module provides a path abstraction that is lightweight and easy to use. Only a single heap allocation is required in many cases, and the module attempts to minimize the overhead of reallocations by doubling the newly needed allocation size upon reallocation. The `c3_path` type will be used in the new epoch-based event log system and also in an upcoming redesign of `unix.c`. It can also be used to simplify to `events.c`. 

Interface:
- `c3_path* c3_path_fa(const c3_c** toks_c, const size_t tok_i)`: create a path from an array of strings.
- `c3_path* c3_path_fv(const size_t tok_i, ...)`: create a path from a variadic list of string arguments.
- `void c3_path_push(c3_path* pax_u, const c3_c* const tok_c)`: push a new component onto the end of a path.
- `void c3_path_pop(c3_path* const pax_u)`: pop a component from the end of a path.

Tests:
See [path_tests.c](https://github.com/urbit/urbit/tree/peter/path/pkg/urbit/tests/path_tests.c).

2022-03-17 14:47 UTC, joemfb requested changes
This all looks reasonable.

We're going to need to review and come to terms with some of the new comment/header style conventions you're been establishing. I guess we can let that play out for some time before attempting to fully resolve those questions.

In a similar vein, I don't really like naming the c3 "library" directory `c/`. The conceit of the `c3` types is that they're "extending" the C language. So maybe this library is "extending" libc?

style nit:

2022-03-17 14:47 UTC, joemfb commented on pkg/urbit/c/path.c
> +  if ( 0 < pax_u->len_i && !_is_root(pax_u->str_c) ) { // (3)
there's no `@n 3` corresponding comment

2022-03-17 23:07 UTC, mcevoypeter commented
> We're going to need to review and come to terms with some of the new comment/header style conventions you're been establishing. I guess we can let that play out for some time before attempting to fully resolve those questions.

Definitely. No convention will be effective unless we're all on the same page. 

> In a similar vein, I don't really like naming the c3 "library" directory `c/`. The conceit of the `c3` types is that they're "extending" the C language. So maybe this library is "extending" libc?

So you're suggesting that modules like `path` and `bile` don't belong in `c3` proper but in a separate directory (and therefore library)? I've been thinking of `c3` as our C programming environment, and so it's felt permissible to put these primitive-ish types in `c3`.

2022-05-18 19:07 UTC, mcevoypeter commented
The final version of this was folded into #5701. Closing this to avoid dealing with annoying cherry-picking/rebasing work.

2022-05-18 19:07 UTC, closed without merging