vere: removes urbit-worker
urbit/urbit pull request #5717
Opened 2022-04-14 13:22 UTC by joemfb

This PR adds all functionality from `urbit-worker` to the main `urbit` binary. It also updates all stateful utility commands (`pack`, `meld`, &c) to open the event log (and thereby aquire the pier lock) before changing state.

The release build still produces a tarball (which is probably worth preserving for a release or two, since people have scripts and automation around it). More to come soon.

2022-04-19 18:33 UTC, mcevoypeter requested changes
Aside from the two comments on `daemon/main.c:_main_bin_path()`, everything LGTM.

2022-04-19 18:33 UTC, mcevoypeter commented on pkg/urbit/daemon/main.c
> +  if ( (4 <= len_w) && !strcmp(bin_c + len_w - 4, ".exe") ) {
The `strcmp` return value check appears to be wrong, which seems to be causing the CI failure on MinGW. It should be `0 != strcmp(bin_c + len_w - 4), ".exe")`.

2022-04-19 18:33 UTC, mcevoypeter commented on pkg/urbit/daemon/main.c
> +}
This doesn't seem to work if `strlen(bin_c) < 4`. I know it's unlikely that we have binary names shorter than four characters, but I think we should still get this right for all cases. Based off preliminary testing, the following should work for all possible lengths of `bin_c`.
```c
#ifdef U3_OS_mingw
  static const c3_c exe_c[] = ".exe";
  size_t len_i = strlen(bin_c);

  c3_c* dot_c = strrchr(bin_c, '.');
  if ( !dot_c || 0 != strcmp(dot_c, exe_c) ) {
    len_i += sizeof(exe_c);
    c3_c* pat_c = c3_malloc(len_i);
    snprintf(pat_c, len_i, "%s%s", bin_c, exe_c);
    return pat_c;
  }
#endif
  return strdup(bin_c);
}
```

2022-04-21 02:45 UTC, joemfb commented
@mcevoypeter you're absolutely right about the binary file-extension handling being wrong. But that wasn't the issue in CI: the worker process was dying in `RegisterWaitForSingleObject()`, trying to setup ctrl-c handling. I've (temporarily) disabled that functionality in the windows build, and removed the file-extension munging. PTAL.

2022-04-22 20:57 UTC, joemfb commented
The windows crashes were a (latent) integer precision bug in `HANDLE` serialization and parsing -- thanks to @locpyl-tidnyd for tracking that down.

2022-04-22 23:10 UTC, mcevoypeter reviewed
LGTM.

2022-04-23 01:58 UTC, merged