vere: exit correctly on fatal error
urbit/urbit pull request #5883
Opened 2022-07-07 05:43 UTC by joemfb

This PR tweaks handling of fatal errors in vere (specifically the "king" process). We now track the presence of a fatal error in global state (`u3_Host.xit_i`, already present and fit for purpose), and make sure to fail any attempted prep-for/upgrade in the presence of errors. (The absence of this logic meant that a binary upgrade could succeed even if preparatory replay failed, which could leave the pilot with a binary that refuses to run linked into the pier.)

2022-07-07 05:44 UTC, joemfb commented on pkg/urbit/vere/disk.c
> +    return;
The cancellation spin loop here was invalid -- libuv only lets you cancel worker threads while they're still queued.

2022-07-07 05:45 UTC, joemfb commented on pkg/urbit/vere/io/term.c
> -    c3_assert( uty_u->car_u );
This unnecessary assertion was an unrelated issue that came up while testing.

2022-07-07 17:17 UTC, mcevoypeter requested changes
Slowly but surely making our way towards better error handling.

2022-07-08 18:51 UTC, joemfb commented on pkg/urbit/vere/disk.c
> +     && uv_cancel(&log_u->req_u) )
Not without dramatic changes elsewhere. This function is called as part of synchronous exit/cleanup, and can be called during error handling. We made all our exit/cleanup functions fully async, then we could always fully cleanup. But this code is changing substantially very soon (mars/urth, log truncation), so it's not worth a major restructuring here.

2022-07-08 21:18 UTC, mcevoypeter reviewed
LGTM. Thanks for addressing the changes I suggested.

2022-07-08 22:00 UTC, merged