dns-address: subscribe before poke
urbit/urbit pull request #5951
Opened 2022-08-17 11:14 UTC by pkova

My newfangled automation of `ship.arvo.network` domains introduced in #5868 exposed a bug in `ted/dns/address`: the thread pokes before subscribing. This often leads to situations where the DNS request is completed before the client subscribes, leaving this thread running forever.

2022-08-17 11:20 UTC, Fang- submitted a review, later dismissed
Classic. Good catch, thank you!

(Gonna hold off on merging for a little bit, but we'll get it out there soon enough.)

2022-08-18 11:15 UTC, tinnus-napbus requested changes

2022-08-18 11:15 UTC, tinnus-napbus commented on pkg/arvo/ted/dns/address.hoon
> +  ;<  ~       bind:m  (watch:strandio /sub collector-app /(scot %p our))
```suggestion
  ;<  ~       bind:m  (watch:strandio /(scot %p our) collector-app /(scot %p our))
```

2022-08-18 11:15 UTC, tinnus-napbus commented on pkg/arvo/ted/dns/address.hoon
> +  ;<  ~       bind:m  (watch:strandio /sub collector-app /(scot %p our))
it subscribes on a different wire than it expects in take-fact so you never get the response

2022-08-18 11:24 UTC, tinnus-napbus commented
the watch was for wire `/sub` but `take-fact` expected wire `/(scot %p our)` so consequently the thread never received the response. I have changed both to `/response` @Fang- pls re-review

2022-08-25 11:28 UTC, Fang- approved these changes
Good catches all around, thank you both.

2022-09-07 17:41 UTC, merged