grid: fix tile bullet + suspend notice layout
urbit/urbit pull request #6109
Opened 2022-11-29 13:35 UTC by tomholford

# Context

This PR addresses a few straggler issues in the integration between Grid and new Clay / Kiln (aka [Agents in Clay](https://roadmap.urbit.org/current#agents-in-clay)).

# Changes

- fix bullet + tile title layout in Grid
- dismiss "n apps blocked system update" notification after update

# Preview

## Before

![image](https://user-images.githubusercontent.com/16504501/204542140-8dfc84ea-9daa-43d5-8b8d-7d4685417fb8.png)

## After 

![Screenshot from 2022-11-29 05-27-50](https://user-images.githubusercontent.com/16504501/204542058-d140d5d6-ef56-47e2-a30c-3cbbb736db40.png)

2022-11-29 16:48 UTC, arthyn approved these changes
lgtm!

2022-11-29 19:20 UTC, philipcmonk requested changes
The suspended dot looks good now, and it correctly dismisses the upgrade notification when clicking "Archive Apps", but it doesn't dismiss the notification when you click "Pause OTAs".

2022-11-29 21:45 UTC, tomholford commented
> The suspended dot looks good now, and it correctly dismisses the upgrade notification when clicking "Archive Apps", but it doesn't dismiss the notification when you click "Pause OTAs".

Good catch, just pushed a commit to address this

2022-12-02 01:33 UTC, tomholford commented
FYI this change has been included in the PR that migrates all 417 clay + kiln changes for Grid to `urbit/garden`

https://github.com/tloncorp/landscape-apps/issues/1271

2022-12-05 21:39 UTC, merged