verb added
urbit/urbit pull request #6306
Opened 2023-02-08 17:46 UTC by tadad

2023-02-16 14:34 UTC, belisarius222 requested changes
A couple minor nits, but this is very close.

2023-02-16 14:34 UTC, belisarius222 commented on pkg/arvo/sys/vane/eyre.hoon
> +      ~>  %slog.[0 leaf+"eyre: {(trip id)} cancelling channel due to timeout"]
This looks like a new print.  I think it should use +trace also.

2023-02-17 14:39 UTC, belisarius222 approved these changes

2023-02-17 14:42 UTC, belisarius222 requested changes
Once CI is fixed, I will approve again.

2023-02-17 16:29 UTC, tadad commented
Apparently there was another state change between when I started this branch and now. `+load` is working now

2023-02-23 14:34 UTC, belisarius222 commented
Tests failed, but it looks spurious -- died after 2 minutes in something other than Arvo.  Rerunning.

2023-03-16 17:39 UTC, belisarius222 approved these changes

2023-03-16 17:39 UTC, merged