gen: extend +vats and |suspend to take lists of desks
urbit/urbit pull request #6478
Opened 2023-04-13 16:12 UTC by silnem2

Extends +vats to take an optional list of one or more desks; if +vats is run with a list of desks and a =filt argument the output will contain only the members of the list that match the filter. Also removes the now-redundant +vat generator, updates |suspend to take a list of desks, and refactors +vats and related functions in /sur/hood. Resolves #6470 and #6477.

2023-04-14 18:17 UTC, jalehman commented on pkg/arvo/gen/vat.hoon
Instead of removing +vat, I'd rather it output a deprecation notice and be refactored in terms of the newly extended `+vats`. That'll prevent breakage to anyone's workflow and teach them how to use the new capabilities in one fell swoop.

2023-04-20 19:49 UTC, jalehman reviewed
This resolves my previous, although I'll defer to @belisarius222 on an actual code review.

2023-04-20 20:42 UTC, belisarius222 approved these changes
I tested this on a fakezod, and it all works right for me.

The non-verbose printing is still wonky, but that behavior is unchanged from the previous version of +vats, so it's not a regression.

2023-04-20 20:49 UTC, belisarius222 requested changes
On second thought, the changes to `|suspend`, while I don't think they're risky, do imply a backward-incompatible change to the Kiln API, which someone might be depending on.  There are three options here:
1) wait until we have confirmation that all "systemically important" agents that are clients of Kiln's `%suspend` API are manually notified so they can change their use of this before release
2) split this into two PRs and merge the `|suspend` changes into a later Kelvin branch
3) revert the changes to Kiln's `%kiln-suspend` poke datatype, and instead change the `|suspend` generator to use a new `%kiln-suspend-many` mark, handled in a new `+poke-suspend-many` arm in Kiln.  `+poke-suspend` can be rewritten to call into that arm with a single-element list of desks to avoid code duplication.

Option 1 isn't great.  Options 2 and 3 are both acceptable.  I would prefer option 3, to reduce compatibility work for client apps.

2023-04-24 15:26 UTC, merged