turn off doccord parsing for +*, =*
urbit/urbit pull request #6509
Opened 2023-04-25 19:16 UTC by drbeefsupreme

see #6307

this turns doccord parsing off for `=*` and `+*`, which was not intended to
be allowed for the first release, but it ended up not compiling if
postfix doccords were put on either of these.

the right way to fix this is to actually implement doccord parsing for
`=*` and `+*`, but at least turning them off seems to fix the compile error here.

94ba944188 changes the signature of `+vang` to add the `doc` flag from
`+vast` and thus changes all the callsites to `+vang` as well.

bff9a0aaa7 changes the parsers for `+*` and `=*`. i considered adding
another arm for `(vang bug wer |)` to avoid repeating it 4 times, but since
this is supposed to be a band-aid and not a permanent fix, i thought it
might be better to avoid adding in new arms that might later be forgotten
when the band-aid is removed. not sure what the right style choice is here.

2023-04-25 19:17 UTC, drbeefsupreme commented
i forked off of `master` instead of `develop`, looks like it brought in https://github.com/urbit/urbit/pull/6509/commits/c2c36f42f524fd588c10aaf927832ad5bc922fd9 for free

2023-04-27 02:06 UTC, drbeefsupreme commented
> i thought it might be better to avoid adding in new arms that might later be forgotten when the band-aid is removed. not sure what the right style choice is here.

he said, after including an unused arm to balance things out. took out `+lien`

2023-05-01 14:41 UTC, joemfb requested changes
This makes sense and looks good. One nit:

2023-05-01 14:41 UTC, joemfb commented on pkg/arvo/sys/hoon.hoon
> +              wide:(vang bug wer |)
No need to call `+vang` again here, you can just use `tall(doc |)` or `wide(doc |)`.

2023-05-01 15:43 UTC, joemfb approved these changes
this will do

2023-05-01 15:58 UTC, belisarius222 commented
@drbeefsupreme This includes an important bugfix, but the change to the `+vang` sample type, while virtuous, is backward-incompatible.  Do you mind splitting the change to `+vang` into a separate PR?  That way we could merge this PR today and get it deployed with kelvin 413.

2023-05-02 15:21 UTC, belisarius222 approved these changes

2023-05-02 15:23 UTC, merged