hoon: add pin and awl arms to test and trim subaxes
urbit/urbit pull request #6592
Opened 2023-05-16 23:10 UTC by eamsden

`+pin`: test if `b` is a sub-axis of `a`
`+awl`: give the remainder axis of `b` under `a` (crash if `b` isn't a sub-axis of `a`)

2023-05-16 23:21 UTC, joemfb requested changes

2023-05-16 23:21 UTC, joemfb commented on pkg/arvo/sys/hoon.hoon
> +  %|
To ensure that the last sub-hoon is the largest, can you switch this to a `?.`? Also, this needs a single `::` line between the `+pin` and `+awl` arms.

2023-05-16 23:21 UTC, joemfb commented on pkg/arvo/sys/hoon.hoon
> +  !!
This should be a `?>`.

2023-05-16 23:21 UTC, joemfb commented on pkg/arvo/sys/hoon.hoon
> +  ::    axis after axis
The should also be a blank `::` line after this "doccord summary".

2023-05-16 23:54 UTC, eamsden commented
just realized `+awl` isn't cvc... don't have any replacement name ideas

2023-05-17 00:20 UTC, joemfb requested changes

2023-05-17 00:20 UTC, joemfb commented on pkg/arvo/sys/hoon.hoon
> +  ?:  =(a 1)  %&
I think `+pin` should be total over non-zero atoms. For that to be the case, this should be

```
?:  =(a 1)  &
?:  =(b 1)  |
```

2023-05-17 00:34 UTC, joemfb approved these changes
These look right to me. They're not urgent, and probably won't go into the next release. They're not particularly useful without jets (which I'd be happy to write). Let's defer to @belisarius222 as to when/where to merge.

this will do

2023-05-17 15:59 UTC, joemfb commented
@eamsden do you expect to always use these gates together? would it be better to combine them into a single gate producing `(unit axis)`?

2023-05-17 17:07 UTC, eamsden commented
> @eamsden do you expect to always use these gates together? would it be better to combine them into a single gate producing `(unit axis)`?

No I expect to use `+pin` by itself quite frequently. `+hub` was frankly only included because it seemed a shame not to when you're already doing all the math.

2023-05-17 18:45 UTC, ashelkovnykov approved these changes
Just making sure I understand correctly: `hub` is `mas of b relative to a`, correct?

2023-05-17 19:02 UTC, eamsden commented
> Just making sure I understand correctly: `hub` is `mas of b relative to a`, correct?

Roughly yes. Instead of taking off 1 bit it takes off however many bits are in `a` (not counting the MSB).

Notably though it crashes if `b` is not a subaxis of `a`.

2023-05-25 12:38 UTC, eamsden commented
@jalehman note that these likely depend on Joe's jets in urbit/vere#397

2023-06-08 15:30 UTC, merged